# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_comm.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic_comm.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x62\x61sic_comm.proto\"\x1b\n\x0e\x43lassification\x12\t\n\x01k\x18\x01 \x01(\x05\"(\n\x07\x46\x65\x61ture\x12\r\n\x05thing\x18\x01 \x01(\x02\x12\x0e\n\x06thing2\x18\x02 \x01(\x02\x32\x35\n\x08\x44\x61taComm\x12)\n\x0cSendFeatures\x12\x08.Feature\x1a\x0f.Classificationb\x06proto3'
)




_CLASSIFICATION = _descriptor.Descriptor(
  name='Classification',
  full_name='Classification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='Classification.k', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thing', full_name='Feature.thing', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thing2', full_name='Feature.thing2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Classification'] = _CLASSIFICATION
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Classification = _reflection.GeneratedProtocolMessageType('Classification', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATION,
  '__module__' : 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:Classification)
  })
_sym_db.RegisterMessage(Classification)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:Feature)
  })
_sym_db.RegisterMessage(Feature)



_DATACOMM = _descriptor.ServiceDescriptor(
  name='DataComm',
  full_name='DataComm',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendFeatures',
    full_name='DataComm.SendFeatures',
    index=0,
    containing_service=None,
    input_type=_FEATURE,
    output_type=_CLASSIFICATION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATACOMM)

DESCRIPTOR.services_by_name['DataComm'] = _DATACOMM

# @@protoc_insertion_point(module_scope)
