#!/bin/bash
#mlagents-learn trainer_config.yaml --run-id=hs_simple --train
mlagents-learn trainer_config.yaml --env=../../environment/HideAndSeekv12/hide_and_seek_built.x86_64 --run-id=hs_simple --train
#tensorboard --logdir=summaries --port 6006
