default:
    trainer: ppo
    batch_size: 1000
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 10000
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

seeker_nav:
    trainer: ppo
    time_horizon: 200
    batch_size: 1000
    buffer_size: 10000
    hidden_units: 256
    num_layers: 1
    beta: 1.0e-2
    max_steps: 1.0e6
    num_epoch: 5
    learning_rate: 1.0e-4 
    epsilon: 0.2
    behavioral_cloning:
        demo_path: ./Demonstration_to_push/Nav1D.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        gail:
            strength: 0.5
            gamma: 0.9
            encoding_size: 128
            use_vail: false
            demo_path: ./Demonstration_to_push/Nav1D.demo


hiderv:
    trainer: ppo        
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    normalize: false
    num_layers: 2
    use_curiosity: true
    use_recurrent: false
    summary_freq: 2000
    sequence_length: 64    
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 1000000
    num_epoch: 5
    behavioral_cloning:
        demo_path: /home/rianhughes/Desktop/Projects/2_AI/MLAgents_Projects/RH_Training_newMlAgents/Assets/Demonstrations/Seeker19CameraTL.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rianhughes/Desktop/Projects/2_AI/MLAgents_Projects/RH_Training_newMlAgents/Assets/Demonstrations/Seeker19CameraTL.demo


seekerv:
    trainer: ppo
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    normalize: false
    num_layers: 2
    use_curiosity: true
    use_recurrent: false
    summary_freq: 2000
    sequence_length: 64
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 1000000
    num_epoch: 5
    behavioral_cloning:
        demo_path: /home/rianhughes/Desktop/Projects/2_AI/MLAgents_Projects/RH_Training_newMlAgents/Assets/Demonstrations/Seeker19CameraTL.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rianhughes/Desktop/Projects/2_AI/MLAgents_Projects/RH_Training_newMlAgents/Assets/Demonstrations/Seeker19CameraTL.demo


Hider34:
    trainer: ppo        
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    normalize: false
    num_layers: 2
    use_curiosity: true
    use_recurrent: false
    summary_freq: 2000
    sequence_length: 64    
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5000000
    num_epoch: 10
    behavioral_cloning:
        demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Hider34Demo.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Hider34Demo.demo


Seeker34:
    trainer: ppo
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    normalize: false
    num_layers: 2
    use_curiosity: true
    use_recurrent: false
    summary_freq: 2000
    sequence_length: 64
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5000000
    num_epoch: 10
    behavioral_cloning:
        demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Seeker34Demo4roo_0.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Seeker34Demo4roo_0.demo


VisualPyramids:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    summary_freq: 2000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 5
    behavioral_cloning:
        demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Pyrvisual.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/Pyrvisual.demo

Pyramids:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    summary_freq: 2000
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 512
    num_layers: 2
    beta: 1.0e-2
    max_steps: 5.0e5
    num_epoch: 3
    behavioral_cloning:
        demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/PyrRH4.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: /home/rian/Desktop/1_Projects/2_Coding_AI_ML/1_OxAI/RH_Training_newMlAgents/Assets/Demonstrations/PyrRH4.demo





CrawlerStatic:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    max_steps: 1e6
    summary_freq: 3000
    num_layers: 3
    hidden_units: 512
    behavioral_cloning:
        demo_path: UnitySDK/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo
        strength: 0.5
        steps: 5000
    reward_signals:
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            demo_path: UnitySDK/Assets/ML-Agents/Examples/Crawler/Demos/ExpertCrawlerSta.demo

PushBlock:
    max_steps: 5.0e4
    batch_size: 128
    buffer_size: 2048
    beta: 1.0e-2
    hidden_units: 256
    summary_freq: 2000
    time_horizon: 64
    num_layers: 2
    reward_signals:
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            demo_path: UnitySDK/Assets/ML-Agents/Examples/PushBlock/Demos/ExpertPush.demo

Hallway:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    memory_size: 256
    beta: 1.0e-2
    num_epoch: 3
    buffer_size: 1024
    batch_size: 128
    max_steps: 5.0e5
    summary_freq: 1000
    time_horizon: 64
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            demo_path: UnitySDK/Assets/ML-Agents/Examples/Hallway/Demos/RiansHallway.demo

FoodCollector:
    batch_size: 64
    summary_freq: 1000
    max_steps: 5.0e4
    use_recurrent: false
    hidden_units: 128
    learning_rate: 3.0e-4
    num_layers: 2
    sequence_length: 32
    reward_signals:
        gail:
            strength: 0.1
            gamma: 0.99
            encoding_size: 128
            demo_path: UnitySDK/Assets/ML-Agents/Examples/FoodCollector/Demos/ExpertFood.demo
    behavioral_cloning:
        demo_path: UnitySDK/Assets/ML-Agents/Examples/FoodCollector/Demos/ExpertFood.demo
        strength: 1.0
        steps: 0
