# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_comm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic_comm.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x62\x61sic_comm.proto\"\x07\n\x05\x45mpty\"(\n\x10\x43onnectionParams\x12\x14\n\x0cis_recording\x18\x01 \x01(\x08\"\x17\n\x08Response\x12\x0b\n\x03res\x18\x01 \x01(\t\"\xb9\x01\n\x10\x43onnectionConfig\x12\x12\n\naction_dim\x18\x01 \x01(\x05\x12\x0f\n\x07obs_dim\x18\x02 \x01(\x05\x12\x13\n\x0bvis_obs_dim\x18\x03 \x01(\x05\x12\x14\n\x0c\x64o_recording\x18\x04 \x01(\x08\x12\x13\n\x0b\x61gent_index\x18\x05 \x01(\x05\x12\x15\n\rnumber_agents\x18\x06 \x01(\x05\x12\x11\n\tdemo_file\x18\x07 \x01(\t\x12\x16\n\x03res\x18\x08 \x01(\x0b\x32\t.Response\"\x1c\n\nNeosAction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\"&\n\x12TextureObservation\x12\x10\n\x08textures\x18\x01 \x03(\x0c\"\x16\n\x07\x42\x61reObs\x12\x0b\n\x03obs\x18\x01 \x03(\x02\"W\n\x0fNeosObservation\x12\x0b\n\x03obs\x18\x01 \x03(\x02\x12\x11\n\tside_info\x18\x02 \x03(\x02\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x14\n\x0cshould_reset\x18\x04 \x01(\x08\x32\xa6\x02\n\x08\x44\x61taComm\x12\"\n\x06GetObs\x12\x06.Empty\x1a\x10.NeosObservation\x12,\n\rGetTextureObs\x12\x06.Empty\x1a\x13.TextureObservation\x12!\n\x07SendAct\x12\x0b.NeosAction\x1a\t.Response\x12!\n\nResetAgent\x12\x08.BareObs\x1a\t.Response\x12;\n\x13\x45stablishConnection\x12\x11.ConnectionParams\x1a\x11.ConnectionConfig\x12#\n\x0eStopConnection\x12\x06.Empty\x1a\t.Response\x12 \n\tGatherAct\x12\x06.Empty\x1a\x0b.NeosActionb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=27,
)


_CONNECTIONPARAMS = _descriptor.Descriptor(
  name='ConnectionParams',
  full_name='ConnectionParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_recording', full_name='ConnectionParams.is_recording', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=69,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='Response.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=94,
)


_CONNECTIONCONFIG = _descriptor.Descriptor(
  name='ConnectionConfig',
  full_name='ConnectionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_dim', full_name='ConnectionConfig.action_dim', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs_dim', full_name='ConnectionConfig.obs_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vis_obs_dim', full_name='ConnectionConfig.vis_obs_dim', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='do_recording', full_name='ConnectionConfig.do_recording', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_index', full_name='ConnectionConfig.agent_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_agents', full_name='ConnectionConfig.number_agents', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='demo_file', full_name='ConnectionConfig.demo_file', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res', full_name='ConnectionConfig.res', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=282,
)


_NEOSACTION = _descriptor.Descriptor(
  name='NeosAction',
  full_name='NeosAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='NeosAction.action', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=312,
)


_TEXTUREOBSERVATION = _descriptor.Descriptor(
  name='TextureObservation',
  full_name='TextureObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='textures', full_name='TextureObservation.textures', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=352,
)


_BAREOBS = _descriptor.Descriptor(
  name='BareObs',
  full_name='BareObs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs', full_name='BareObs.obs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=376,
)


_NEOSOBSERVATION = _descriptor.Descriptor(
  name='NeosObservation',
  full_name='NeosObservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='obs', full_name='NeosObservation.obs', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='side_info', full_name='NeosObservation.side_info', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='NeosObservation.reward', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='should_reset', full_name='NeosObservation.should_reset', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=465,
)

_CONNECTIONCONFIG.fields_by_name['res'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ConnectionParams'] = _CONNECTIONPARAMS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ConnectionConfig'] = _CONNECTIONCONFIG
DESCRIPTOR.message_types_by_name['NeosAction'] = _NEOSACTION
DESCRIPTOR.message_types_by_name['TextureObservation'] = _TEXTUREOBSERVATION
DESCRIPTOR.message_types_by_name['BareObs'] = _BAREOBS
DESCRIPTOR.message_types_by_name['NeosObservation'] = _NEOSOBSERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

ConnectionParams = _reflection.GeneratedProtocolMessageType('ConnectionParams', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONPARAMS,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionParams)
  ))
_sym_db.RegisterMessage(ConnectionParams)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)

ConnectionConfig = _reflection.GeneratedProtocolMessageType('ConnectionConfig', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTIONCONFIG,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:ConnectionConfig)
  ))
_sym_db.RegisterMessage(ConnectionConfig)

NeosAction = _reflection.GeneratedProtocolMessageType('NeosAction', (_message.Message,), dict(
  DESCRIPTOR = _NEOSACTION,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:NeosAction)
  ))
_sym_db.RegisterMessage(NeosAction)

TextureObservation = _reflection.GeneratedProtocolMessageType('TextureObservation', (_message.Message,), dict(
  DESCRIPTOR = _TEXTUREOBSERVATION,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:TextureObservation)
  ))
_sym_db.RegisterMessage(TextureObservation)

BareObs = _reflection.GeneratedProtocolMessageType('BareObs', (_message.Message,), dict(
  DESCRIPTOR = _BAREOBS,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:BareObs)
  ))
_sym_db.RegisterMessage(BareObs)

NeosObservation = _reflection.GeneratedProtocolMessageType('NeosObservation', (_message.Message,), dict(
  DESCRIPTOR = _NEOSOBSERVATION,
  __module__ = 'basic_comm_pb2'
  # @@protoc_insertion_point(class_scope:NeosObservation)
  ))
_sym_db.RegisterMessage(NeosObservation)



_DATACOMM = _descriptor.ServiceDescriptor(
  name='DataComm',
  full_name='DataComm',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=468,
  serialized_end=762,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetObs',
    full_name='DataComm.GetObs',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NEOSOBSERVATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTextureObs',
    full_name='DataComm.GetTextureObs',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TEXTUREOBSERVATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendAct',
    full_name='DataComm.SendAct',
    index=2,
    containing_service=None,
    input_type=_NEOSACTION,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetAgent',
    full_name='DataComm.ResetAgent',
    index=3,
    containing_service=None,
    input_type=_BAREOBS,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EstablishConnection',
    full_name='DataComm.EstablishConnection',
    index=4,
    containing_service=None,
    input_type=_CONNECTIONPARAMS,
    output_type=_CONNECTIONCONFIG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StopConnection',
    full_name='DataComm.StopConnection',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GatherAct',
    full_name='DataComm.GatherAct',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_NEOSACTION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATACOMM)

DESCRIPTOR.services_by_name['DataComm'] = _DATACOMM

# @@protoc_insertion_point(module_scope)
