# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import basic_comm_pb2 as basic__comm__pb2


class DataCommStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendFeatures = channel.unary_unary(
        '/DataComm/SendFeatures',
        request_serializer=basic__comm__pb2.Feature.SerializeToString,
        response_deserializer=basic__comm__pb2.Classification.FromString,
        )


class DataCommServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendFeatures(self, request, context):
    """(Method definitions not shown)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataCommServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendFeatures': grpc.unary_unary_rpc_method_handler(
          servicer.SendFeatures,
          request_deserializer=basic__comm__pb2.Feature.FromString,
          response_serializer=basic__comm__pb2.Classification.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DataComm', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
